### ISSUE TITLE
/usr/lib/python: not found on Ubuntu 16.04 cloudimage

### ISSUE THREAD

**Issue by GhostPunk** [attadev/ansible-playbooks#1]
only python3 installed default in Ubuntu 16.04 cloudimage, so we get the following error when we try to run ansible:
`fatal: [test4]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "sudo: unable to resolve host u1604-1\r\n/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "parsed": false}`

(ignore the unable to resolve host error)

**Workaround:**
Install python manually 

**Proposed fix:**

**Comment by diemogebhardt** [comment]
@GhostPunk 

This might be a better workaround:

```
[ubuntu:vars]
ansible_python_interpreter=/usr/bin/python2.7

[ubuntu]
somehost
```

```
---
- hosts: ubuntu
  gather_facts: False
  tasks:
    - name: Update apt-get
      raw: apt-get update -qq
    - name: Install python 2.7
      raw: apt-get install -qq python2.7
```
